version: '3'

services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    build: requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    #  - site:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        MDB_DATABASE: ${MDB_DATABASE}
        MDB_ADMIN: ${MDB_ADMIN}
        MDB_MDP: ${MDB_MDP}
        MDB_ROOT_MDP: ${MDB_ROOT_MDP}
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  site:
    container_name: site
    build: requirements/bonus/static-site
    restart: always
    networks:
      - inception
    depends_on:
      - nginx
    #volumes:
    #  - site:/var/www/html
    ports:
      - "150:150"
  
networks:
  inception:

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind
  #site:
  #  driver_opts:
  #    type: none
  #    device: /home/adaloui/data/
  #    o: bind