version: '3'

services:
#  nginx:
#    container_name: nginx
#    ports:
#      - "443:443"
#   restart: always
#    networks:
#      - inception
#    build: requirements/nginx/.
  mariadb:
    container_name: mariadb
    ports:
      - "3306"
    restart: always
    networks:
      - inception
    build: ./requirements/mariadb/.
    env_file:
      - .env
networks:
  inception: