version: '3'

services:
#  nginx:
#    container_name: nginx
#    expose:
#      - "443"
#    restart: always
#    networks:
#      - inception
#    build: requirements/nginx/.
#  mariadb:
#    container_name: mariadb
#    expose:
#      - "3306"
#    restart: unless-stopped
#    networks:
#      - inception
#    env_file:
#      - .env
#    build:  ./requirements/mariadb/.
  wordpress:
    container_name: wordpress
    expose:
      - "9000"
    #restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build: ./requirements/wordpress
networks:
  inception: