version: '3'

services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    build: requirements/nginx/.
  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:  ./requirements/mariadb/.
  wordpress:
    container_name: wordpress
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build: ./requirements/wordpress
networks:
  inception:

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind
  wp-files-volume:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind