version: '3'

services:
#  nginx:
#    container_name: nginx
#    expose:
#      - "443"
#    restart: always
#    networks:
#      - inception
#    build: requirements/nginx/.
  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:  ./requirements/mariadb/.
    #environment:
    #  - ROOT_IN_MARIADB=${ROOT_IN_MARIADB}
    #  - ROOT_PASSWORD_IN_MARIADB=${ROOT_PASSWORD_IN_MARIADB}
    #  - USER_IN_MARIADB=${USER_IN_MARIADB}
    #  - USER_PASSWORD_IN_MARIADB=${USER_PASSWORD_IN_MARIADB}
    #  - DATABASE_IN_MARIADB=${DATABASE_IN_MARIADB}
networks:
  inception: