version: '3'

services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    build: requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    expose:
      - "9000"
    restart: unless-stopped
    networks:
      - inception
    env_file:
      - .env
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
networks:
  inception:

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/adaloui/data/
      o: bind