/*CREATE DATABASE IF NOT EXISTS Adnen_base;
CREATE USER IF NOT EXISTS 'Sasuke'@'%' IDENTIFIED BY 'popo';
GRANT ALL PRIVILEGES ON Adnen_base.* TO 'Sasuke'@'%';*/
/*FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpopo';
*/
/*CREATE DATABASE Base;
CREATE USER 'bca'@'%' IDENTIFIED BY '1qaz';
GRANT ALL PRIVILEGES ON Base.* TO 'bca'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '1qaz2wsx';*/



CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'adaloui'@'%' IDENTIFIED BY 'popo';
GRANT ALL PRIVILEGES ON wordpress.* TO 'adaloui'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpopo';
FLUSH PRIVILEGES;

